CREATE TABLE IF NOT EXISTS Notification (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES Account(id) NOT NULL,
  type VARCHAR(255) NOT NULL,
  message VARCHAR(255),
  status BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);
