CREATE TABLE IF NOT EXISTS Workshop (
  id SERIAL PRIMARY KEY,
  inventory_id INT REFERENCES Tire_Inventory(id) NOT NULL,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  contact_number VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);
