CREATE TABLE IF NOT EXISTS Tire_Inventory (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES Account(id) NOT NULL,
  tire_id INT REFERENCES Tire_Model(id) NOT NULL,
  note STRING,
  is_saved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);
